integer        ::= '-'? [1-9] [0-9]*
identifier     ::= [a-zA-Z_][_a-zA-Z0-9]* | ( "'" [^']+ "'" )

type_def       ::= 'type' identifier type_ref
type_instance  ::= ( ( 'struct'    '{' ( identifier type_ref )+ '}' )
                   | ( 'polymorph' '{'   identifier+            '}' ))
type_ref       ::= ( ( type_instance | identifier ) '?'? ) | (( '^' | '*' ) type_ref )

function_decl  ::= 'fn' identifier? '(' ( identifier type_ref ( ',' identifier type_ref )* )? ')' type_expr
function       ::= function_decl block

block          ::= '{' statement* '}'
statement      ::=
 ( ('set' | 'const' | 'var')? identifier '=' expression )
 | ( 'loop' block )
 | ( 'match' expression ( 'as' identifier )? '{' ( type_expr block )+ '}' )
 | if_statement
 | callsite
 | ( 'return' expression? )
 | 'continue'
 | 'break'

if_statement ::= 'if' expression block 'else' ( block | if_statement )
callsite     ::= expression '(' ( expression ( ',' expression )* )? ')'

/* Expressions are autoreleased if the type obeys */
expression ::=
   literal
 | ref_expr
 | callsite
 | ( '(' expression ')' )
 | ( 'if' 'expression' 'then' 'expression' 'else' 'expression' )
 | ( 'let' '{' statement* 'in' expression '}' )

literal        ::= integer | string | boolean | float | 'nil' type_expr | '&' expression
module         ::= ( module_decl (link_module | link_function)* (type_def | function)* )
module_decl    ::= 'module' identifier
link_module    ::= 'link' filename
link_function  ::= 'link' function_decl
