integer        ::= '-'? [1-9] [0-9]*
identifier     ::= [a-zA-Z_][_a-zA-Z0-9]* | ( "'" [^']+ "'" )

type_def       ::=
   'type' identifier ( ( 'struct'   '{' ( identifier type_expr )+ '}' )
                     | ( 'polymorph '{'   identifier+             '}' ) )

type_expr      ::= ( ( ( '^' | '*' ) type_expr ) | identifier )
function_decl  ::= 'fn' identifier? '(' ( identifier type_expr ( ',' identifier type_expr )* )? ')' type_expr
function       ::= function_decl block

block          ::= '{' statement* '}'
statement      ::=
 ( ('set' | 'const' | 'var')? identifier '=' expression )
 | ( 'loop' block )
 | ( 'match' expression ( 'as' identifier )? '{' ( type_expr block )+ '}' )
 | if_statement
 | callsite
 | ( 'return' expression? )
 | 'continue'
 | 'break'

if_statement ::= 'if' expression block 'else' ( block | if_statement )
callsite     ::= 'call' expression '(' ( expression ( ',' expression )* )? ')'

/* Expressions are autoreleased if the type obeys */
expression ::=
   literal
 | ref_expr
 | callsite
 | ( 'if' 'expression' 'then' 'expression' 'else' 'expression' )
 | ( 'let' '{' statement* 'in' expression '}' )

ref_expr       ::= identifier ( '.' identifier )*
literal        ::= integer | string | boolean | float | 'nil' type_expr | '&' expression

module         ::= ( module_decl (link_module | link_function)* (type_def | function)* )
module_decl    ::= 'module' identifier
link_module    ::= 'link' filename
link_function  ::= 'link' function_decl
